default:
  image: duskmoon/dev-env:rcore-ci

stages:
  - test

test-code-job:
  stage: test
  script:
    - git clone https://github.com/LearningOS/rCore-Tutorial-Checker-2024S.git ci-user
    - git clone https://github.com/LearningOS/rCore-Tutorial-Test-2024S.git ci-user/user
    - cp -r $HOME/os-vendor os/vendor
    - cp -r $HOME/user-vendor ci-user/user/vendor
    - cd ci-user && make test CHAPTER=`echo $CI_COMMIT_REF_NAME | grep -oP 'ch\K[0-9]'` passwd=$BASE_TEST_TOKEN OFFLINE=1
